---
- name: update grub config
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* console)\"[^\"]+)(\".*)'
    line: '\1 console=ttyS0\2'
  notify: update grub config