---
collections:
  - name: usegalaxy_eu.handy
    version: 2.7.1
    source: https://galaxy.ansible.com
roles:
  - src: usegalaxy_eu.cuda
    version: 1.0.1
  - src: https://github.com/usegalaxy-eu/ansible-nvidia-container.git
    name: usegalaxy-eu.nvidia-container
    version: c2c1bbe259012971f70d42e8f5f442f8834505d2
  - src: geerlingguy.docker
    version: 4.1.1
  - src: https://github.com/usegalaxy-eu/ansible-chrony
    name: influxdata.chrony
    version: 0.1.0
  - src: https://github.com/galaxyproject/ansible-pulsar.git
    name: galaxyproject.pulsar
    version: 1.0.9
  - src: https://github.com/usegalaxy-eu/ansible-dynmotd
    name: usegalaxy-eu.dynmotd
    version: 0.0.1
  - src: usegalaxy_eu.htcondor
    name: usegalaxy-eu.htcondor
    version: 0.0.5
  - src: geerlingguy.repo-epel
    version: 3.1.0
  - src: geerlingguy.java
    version: 1.10.0
  - src: galaxyproject.cvmfs
    version: 0.2.13
  - src: https://github.com/usegalaxy-eu/ansible-autofs
    name: usegalaxy-eu.autofs
    version: 0.0.9
