- src: https://github.com/usegalaxy-eu/ansible-cuda.git
  name: usegalaxy-eu.cuda
  version: 12aa20c5a937e53680cadfc23ab121495b2aea76
- src: https://github.com/usegalaxy-eu/ansible-nvidia-container.git
  name: usegalaxy-eu.nvidia-container
  version: c2c1bbe259012971f70d42e8f5f442f8834505d2
- src: geerlingguy.docker
  version: 2.8.1
- src: https://github.com/usegalaxy-eu/ansible-chrony
  name: influxdata.chrony
  version: "0.1"
- src: https://github.com/galaxyproject/ansible-pulsar.git
  name: galaxyproject.pulsar
  version: 1.0.6
- src: https://github.com/usegalaxy-eu/ansible-remap-user.git
  name: usegalaxy-eu.remap-user
  version: main
- src: https://github.com/usegalaxy-eu/ansible-dynmotd
  name: usegalaxy-eu.dynmotd
  version: master
- src: https://github.com/usegalaxy-eu/ansible-htcondor
  name: usegalaxy-eu.htcondor
  version: 0.0.3
- src: geerlingguy.repo-epel
  version: 3.0.0
- src: geerlingguy.java
  version: 1.10.0
- src: galaxyproject.cvmfs
  version: 0.2.13
