---
- hosts: default
  vars:
    internal: true
  vars_files:
    - "group_vars/all.yml"
  post_tasks:
    - copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
        mode: '0644'

  roles:
    - lock-root
    - ssh-host-sign
    - cloudinit
