# Setup for Virtual Galaxy Compute Node
# This setup is valid for RHEL 7.x based systems.
---
- hosts: default

  vars_files:
    - "group_vars/all.yml"
    - "group_vars/pulsar.yml"
    - "group_vars/condor.yml"
    - "group_vars/cuda.yml"
  pre_tasks:
    - name: Install Pulsar dependencies
      become: yes
      package:
        state: latest
        name:
        - git
        - python36
        - python3-devel
        - python3-virtualenv
        - gcc
        - curl
        - libcurl-devel
        - openssl-devel
    - name: Set default version of Python
      alternatives:
        name: python
        path: /usr/bin/python3
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive
  post_tasks:
    - name: galaxy account group
      group:
        gid: "{{ galaxy_gid }}"
        name: galaxy
        state: present
    - name: galaxy account user
      user:
        uid: "{{ galaxy_uid }}"
        name: galaxy
        group: galaxy
        home: /opt/galaxy
        state: present
        comment: Galaxy Service-Acct
        createhome: no
    - user:
        name: galaxy
        groups: condor,docker
        append: yes
    - user:
        name: centos
        groups: docker
        append: yes
    - yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - python3-devel
        - gcc
        - libcurl-devel
        - openssl-devel
      become: yes
    - name: Copy Docker daemon.json
      copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
        mode: '0644'
    - name: Restart Docker service, in all cases
      service:
        name: docker
        state: restarted
    - name: Disable firewalld service
      systemd:
        name: firewalld
        enabled: no
        state: stopped
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive
    - name: Copy
      copy:
        content: |
          #!/bin/bash
          echo '{"alive":1}'
        dest: /bin/iamalive
        owner: telegraf
        group: telegraf
        mode: 0755
  roles:
    - basic
    ## Dependencies
    - geerlingguy.repo-epel # Install EPEL
    - usegalaxy-eu.powertools # geerlingguy.repo-epel role doesn't enable (yet) PowerTools repository
    - usegalaxy-eu.htcondor
    - systemupdate
    - maintenance
    - usegalaxy-eu.dynmotd
    - dj-wasabi.telegraf
    - influxdata.chrony
    - geerlingguy.java
    - geerlingguy.docker
    - galaxyproject.cvmfs
    - galaxyproject.pulsar
    - usegalaxy-eu.limits
    - usegalaxy-eu.cuda
    - usegalaxy-eu.nvidia-container
    # needs to be at the end, otherwise dnsmasq will occupy 999 slot
    - usegalaxy-eu.remap-user
    - usegalaxy-eu.update-grub

