# Setup for Virtual Jenkins Compute Node
# This setup is valid for RHEL 8.x based systems.
---
- hosts: default

  vars:
    jenkins_public_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfQrCU7MkCPHoFt6kwBnh3kZMd38WMbP4TSmaYrRjqwNAqlW9zoyHMy/eU+Gvb87hjSm9EZG8GOoHAkkqy1s7G6qQWNfYoxyQmbxs/nj3mtvFRKfow8WUmt2Xew5tXWJX1GxWtpyNn4ytrB7iGJRyiGN1R/g6qyBu/rxWtVvWxz79THajJqt5zgJFvnnLDOj9wlUIdA6lXlMOE0fUzdXsBNhZGWMwMCo+hd3i+SHsuK5QvBGPz/c9SdfzyKfg8JFmb2dfMCfybhsAeGO315qZWe1t7fgwVYiFRcOvTpZ0SR7sFPfmEAzm4sIF10n1EIADB70tfmsWsPX42oC/l4Zp1"
    software_groups_to_install:
      - admin
      - editors
      - terminals
      - utils

  vars_files:
    - "group_vars/all.yml"
    - "group_vars/java.yml"

  pre_tasks:
    - name: system update
      ansible.builtin.dnf:
        name: '*'
        state: latest
    - name: Install some dependencies
      become: yes
      ansible.builtin.dnf:
        state: latest
        name:
          - git
          - python38
          - python3-devel
          - python3-virtualenv
          - gcc
          - curl
          - libcurl-devel
          - openssl-devel
          - qemu-kvm
          - qemu-img
          - unzip
          - seabios
    - name: Set default version of Python
      ansible.builtin.alternatives:
        name: python
        path: /usr/bin/python3.8
    - name: Ensure SELinux is set to enforcing mode
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=enforcing

  post_tasks:
    - name: Set default version of Python
      ansible.builtin.alternatives:
        name: java
        path: /usr/lib/jvm/java-11-openjdk/bin/java

    - name: Download packer
      ansible.builtin.shell: wget https://releases.hashicorp.com/packer/1.7.10/packer_1.7.10_linux_amd64.zip -O /tmp/packer.zip

    - name: Extract packer
      ansible.builtin.shell: unzip /tmp/packer.zip -d /usr/bin

    - name: Adding existing user centos to group kvm
      ansible.builtin.user:
        name: centos
        groups: kvm
        append: yes

    - name: Set authorized key taken from var
      ansible.posix.authorized_key:
        user: centos
        state: present
        key: "{{ jenkins_public_ssh_key }}"

  roles:
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_powertools: true
        enable_install_software: true
        enable_grub: true
        enable_kernel_5: true

    - geerlingguy.repo-epel # Install EPEL
    - usegalaxy-eu.autoupdates  # keep all of our packages up to date
    - usegalaxy-eu.dynmotd
    - geerlingguy.java
    - geerlingguy.docker
    - dj-wasabi.telegraf
    - influxdata.chrony

