# Setup for Virtual Jenkins Compute Node
---
- hosts: default

  vars:
    jenkins: true

  vars_files:
    - "group_vars/all.yml"
    - "group_vars/java.yml"

  pre_tasks:
    - name: system update
      ansible.builtin.dnf:
        name: '*'
        state: latest
    - name: Install some dependencies
      become: yes
      ansible.builtin.dnf:
        state: latest
        name:
          - git
          - python38
          - python3-devel
          - python3-virtualenv
          - gcc
          - curl
          - libcurl-devel
          - openssl-devel
          - qemu-kvm
          - qemu-img
          - unzip
          - seabios
    - name: Set default version of Python
      ansible.builtin.alternatives:
        name: python
        path: /usr/bin/python3.8
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.posix.selinux:
        policy: targeted
        state: permissive

  post_tasks:
    - name: Download packer
      ansible.builtin.shell: wget https://releases.hashicorp.com/packer/1.7.10/packer_1.7.10_linux_amd64.zip -O /tmp/packer.zip

    - name: Extract packer
      ansible.builtin.shell: unzip /tmp/packer.zip -d /usr/bin

    - name: Adding existing user centos to group kvm
      ansible.builtin.user:
        name: centos
        groups: kvm
        append: yes

  roles:
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_powertools: true
        enable_install_software: true

    - geerlingguy.repo-epel # Install EPEL
    - usegalaxy-eu.dynmotd
    - geerlingguy.java
    - geerlingguy.docker
    - dj-wasabi.telegraf
    - influxdata.chrony

