# Setup for Virtual Galaxy Compute Node
# This setup is valid for RHEL 7.x based systems.
---
- hosts: default

  vars_files:
    - "group_vars/all.yml"
    - "group_vars/pulsar.yml"
    - "group_vars/condor.yml"
    - "group_vars/cuda.yml"
  post_tasks:
    - user:
        name: galaxy
        groups: condor,docker
        append: yes
    - user:
        name: centos
        groups: docker
        append: yes
    - command: "yum clean all"
  roles:
    - galaxy
    - basic
    - htcondor
    - systemupdate
    - dynmotd
    - dj-wasabi.telegraf
    - influxdata.chrony
    - geerlingguy.java
    - geerlingguy.docker
    - docker-prune
    - cvmfs
    - galaxyproject.pulsar
    - usegalaxy-eu.limits
    - usegalaxy-eu.cuda
    - usegalaxy-eu.nvidia-container
