---
vg_build: 60
# This will be replaced by jenkins.
build_tag:  vggp-v##-j##-##-branch

cloud: bwCloud

galaxy_uid: 999
galaxy_gid: 999

replace_non_galaxy_999: true

telegraf_agent_package_state: latest
telegraf_agent_tags:
  - tag_name: datacenter
    tag_value: rz
  - tag_name: cloud
    tag_value: "{{ cloud }}"
  - tag_name: vgcn_build
    tag_value: "{{ build_tag }}"
  - tag_name: distribution
    tag_value: "{{ ansible_distribution }}"
  - tag_name: distribution_version
    tag_value: "{{ ansible_distribution_version }}"

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: diskio
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat
  - plugin: processes
  - plugin: kernel
  - plugin: chrony
  - plugin: exec
    config:
      - commands = ["/bin/iamalive"]
      - name_suffix = "_alive"

java_packages:
 - java-11-openjdk
 - java-11-openjdk-devel

# CVMFS
cvmfs_role: client
galaxy_cvmfs_repos_enabled: true
galaxy_cvmfs_server_urls:
  - domain: galaxyproject.org
    urls:
      - "http://cvmfs1-ufr0.galaxyproject.eu/cvmfs/@fqrn@"
      - "http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs-s1-galaxy.computecanada.ca:8000/cvmfs/@fqrn@"
      - "http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-mel0.gvl.org.au/cvmfs/@fqrn@"

# dynmotd
dynmotd_custom:
  - name: Build
    command: "echo VGGP build {{ cloud }} {{ build_tag }}"
  - name: Build date
    command: "echo  {{ ansible_date_time.iso8601 }}"

# Docker
docker_users:
  - centos
  - condor

nodejs_version: "8.x"
nodejs_install_npm_user: root
nodejs_npm_global_packages:
 - yarn

texlive_directory: /usr/local/texlive
texlive_mirror: "http://packages.oth-regensburg.de/ctan/systems/texlive/tlnet/"
texlive_rsync: "rsync://packages.oth-regensburg.de/ctan/systems/texlive/tlnet/"
scheme: full

# Filesystem maintenance
jwd_path: "/scratch/galaxy_db/job_working_directory/"
tmp_path: "/scratch/galaxy_db/tmp/"
mtime: "+30"

# Chrony
chrony_server: 'time.ruf.uni-freiburg.de iburst'
chrony_acquisitionport: 0
chrony_conf_file: '/etc/chrony.conf'
chrony_keyfile: '/etc/chrony.keys'

#usegalaxy_eu.handy.os_setup
# Autofs
autofs_service.install: True
autofs_service.enable: True
nfs_kernel_tuning: True
nfs_kernel_tuning_parameters:
  sunrpc.tcp_max_slot_table_entries: 100

# usegalaxy_eu.handy.os_setup
# ansible_root_cron
ansible_root_cron:
  - name: "Prune unused Docker objects"
    weekday: "{{ 7 | random }}"
    minute: "{{ 60 | random }}"
    hour: "{{ 5 | random }}"
    job: "docker system prune -f"
  - name: "Stop containers running more than 1 months"
    weekday: "{{ 7 | random }}"
    minute: "{{ 60 | random }}"
    hour: "{{ 5 | random }}"
    job: "/usr/bin/docker-stop-1M"
  - name: "Vacuum logs older than 7 days"
    weekday: "{{ 7 | random }}"
    minute: "{{ 15 | random }}"
    hour: "{{ 2 | random }}"
    job: '/usr/bin/journalctl --vacuum-time="7 days"'

## packages
software_groups_to_install:
  - admin
  - apps
  - debug
  - development
  - editors
  - fonts
  - services
  - utils

## kernel_5
kernel_5_package: kernel-ml

docker_daemon_options: {}

