---
  - name: cloud-init install
    package:
      name: cloud-init
      state: latest
      use: yum

  - name: cloud-utils-growpart install
    package:
      name: cloud-utils-growpart
      state: latest
      use: yum

  # Centos
  - name: cloud-init config 1
    when: ansible_distribution == 'CentOS'
    blockinfile:
      dest: /etc/cloud/cloud.cfg
      block: |
        system_info:
          default_user:
            name: centos
            gecos: CentOS Cloud User
            groups: [wheel, adm, systemd-journal]
            sudo: ["ALL=(ALL) NOPASSWD:ALL"]
            shell: /bin/bash
          distro: rhel
          paths:
            cloud_dir: /var/lib/cloud
            templates_dir: /etc/cloud/templates
          ssh_svcname: sshd

  - name: cloud-init config 2
    lineinfile:
      dest: /etc/cloud/cloud.cfg
      line: 'manage_etc_hosts: true'
      insertafter: '^syslog_fix_perms:.*$'

  - name: cloud-init config 3
    blockinfile:
      dest: /etc/cloud/cloud.cfg
      block: |
        runcmd:
         - 'sed -i "s|localhost.localdomain|$(hostname -f)|g" /etc/telegraf/telegraf.conf'
         - 'systemctl restart telegraf'

  - name: cloud-init config 4
    blockinfile:
      dest: /etc/cloud/cloud.cfg
      block: |
        disk_setup:
          /dev/vdb:
            table_type: mbr
            layout: True
            overwrite: True
        fs_setup:
          - label: None
            filesystem: xfs
            device: /dev/vdb
            partition: auto
        runcmd:
          - mkdir /scratch/galaxy_db/job_working_directory
        mounts:
          - [ /dev/xvdb, /scratch/galaxy_db/job_working_directory, xfs, "defaults", "0", "2" ]
