---
- hosts: internal
  vars:
    internal: true
  vars_files:
    - "group_vars/all.yml"
    - "group_vars/condor.yml"
  pre_tasks:
    - name: Include secret vars
      ansible.builtin.include_vars: "secret_group_vars/internal.yml"
      when: "'internal' in group_names"
    - name: Copy server key into VM temporarily
      ansible.builtin.copy:
        src: server_ca
        dest: /tmp/server_ca
        owner: root
        group: root
        mode: "0600"
    - name: Add HostCertificate options
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^HostKey /etc/ssh/ssh_host_{{ item }}_key"
        line: "HostKey /etc/ssh/ssh_host_{{ item }}_key\nHostCertificate /etc/ssh/ssh_host_{{ item }}_key-cert.pub"
      with_items:
        - rsa
        - ecdsa
        - ed25519
    - name: Add core limit
      community.general.pam_limits:
        domain: galaxy
        limit_type: hard
        limit_item: core
        value: 0

  roles:
    - lock-root
    - cloudinit

- name: HTCondor cluster.
  hosts: workers:&internal
  vars:
    internal: true
  vars_files:
    - "group_vars/all.yml"
    - "group_vars/condor.yml"
    - "secret_group_vars/internal.yml"
  handlers:
    - name: Reload HTCondor
      when: "'condor_service' in service_facts.ansible_facts.services and \
        service_facts.ansible_facts.services['condor.service'].state == 'running'"
      become: true
      ansible.builtin.service:
        name: condor
        state: reloaded
  pre_tasks:
    - name: Ensure the HTCondor configuration directory exists.
      become: true
      ansible.builtin.file:
        path: /etc/condor
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Template HTCondor configuration.
      become: true
      ansible.builtin.template:
        src: htcondor/condor_config.local.j2
        dest: /etc/condor/condor_config.local
        owner: root
        group: root
        mode: "0644"
      notify: Reload HTCondor
    - name: Check if HTCondor is running.
      ansible.builtin.service_facts:
      register: service_facts
  roles:
    - grycap.htcondor
